export { default as Home } from './Home'
export { default as About } from './About'
export { default as Posts } from './Posts'
export { default as Profile } from './Profile'
export { default as PostDetail } from './PostDetail'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
